module.exports = {
	singleQuote: true,
	semi: false,
	plugins: ['prettier-plugin-tailwindcss'],
	trailingComma: 'es5',
	tabWidth: 2,
	useTabs: true,
	printWidth: 80,
	arrowParens: 'avoid',
	bracketSpacing: true,
	jsxSingleQuote: false,
	proseWrap: 'preserve',
	quoteProps: 'as-needed',
	requirePragma: false,
	insertPragma: false,
	endOfLine: 'lf',
	htmlWhitespaceSensitivity: 'css',
	vueIndentScriptAndStyle: false,
	embeddedLanguageFormatting: 'auto',
}
