import react from '@vitejs/plugin-react'

import { defineConfig } from 'vitest/config'
import { transformWithOxc } from 'vite'
import { fileURLToPath } from 'url'
import path from 'path'

const rootDir = path.dirname(fileURLToPath(import.meta.url))

// The app writes JSX in `.js` files (Next.js compiles them), but Vite only
// parses JSX in `.jsx`/`.tsx`. Transform the app sources as JSX so component
// tests can render them.
const jsxInJsSources = {
	async transform(code, id) {
		const file = id.split('?')[0]
		if (!file.startsWith(path.resolve(rootDir, 'src')) || !file.endsWith('.js'))
			return null
		const result = await transformWithOxc(code, file, {
			jsx: { runtime: 'automatic' },
			lang: 'jsx',
		})
		return { code: result.code, map: result.map }
	},
	name: 'forvoyez:jsx-in-js-sources',
	enforce: 'pre',
}

export default defineConfig({
	resolve: {
		alias: {
			// During unit tests we don't need the real Clerk package; point imports
			// to local lightweight mocks so Vitest / Vite can resolve them.
			'@clerk/nextjs/server': path.resolve(
				rootDir,
				'./tests/unit/mocks/clerk.server.js'
			),
			'@clerk/nextjs': path.resolve(
				rootDir,
				'./tests/unit/mocks/clerk.client.js'
			),
			// Next.js resolves `server-only` itself (no npm package installed).
			'server-only': path.resolve(rootDir, './tests/unit/mocks/server-only.js'),
			'@': path.resolve(rootDir, './src'),
		},
	},
	test: {
		coverage: {
			reporter: [
				'text',
				'json-summary',
				'json',
				'clover',
				'cobertura',
				'html',
				'html-spa',
				'lcov',
			],
			// the Prisma client generated by `prisma generate` is not app code
			exclude: ['src/generated/**'],
			provider: 'v8',
		},
		include: ['tests/unit/**/*.test.js'],
		environment: 'jsdom',
	},
	plugins: [jsxInJsSources, react()],
})
