name: Build
env:
  TOTAL_RUNNERS: 1
  NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}

#on:
#  pull_request:
#    branches: ['main']

on:
  push:
    branches: [feat/cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Just Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: test
     #     tags: ${{ secrets.APP_IMAGE }}
