name: 'Test'

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, gulp, prettier, vitest]
      - name: 'Run Unit Tests'
        run: pnpm test:ci
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
      - name: 'Lint Code'
        run: pnpm lint

  test-e2e:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Docker'
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: 'Install Dependencies'
        run: |
          pnpm install --frozen-lockfile
      - name: 'Install Playwright Browsers'
        run: pnpm exec playwright install
      - name: 'Build Docker Image for testing'
        run: |
          docker build -f Dockerfile.test -t forvoyez:test \
            --build-arg NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_OUT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_OUT_URL }} \
            --build-arg MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }} \
            --build-arg MAILGUN_API_URL=${{ secrets.MAILGUN_API_URL }} \
            --build-arg MAILGUN_PUBLIC_KEY=${{ secrets.MAILGUN_PUBLIC_KEY }} \
            --build-arg MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg LEMON_SQUEEZY_API_KEY=${{ secrets.LEMON_SQUEEZY_API_KEY }} \
            --build-arg LEMON_SQUEEZY_STORE_ID=${{ secrets.LEMON_SQUEEZY_STORE_ID }} \
            --build-arg LEMON_SQUEEZY_WEBHOOK_SECRET=${{ secrets.LEMON_SQUEEZY_WEBHOOK_SECRET }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg TEST_EMAIL=${{ secrets.TEST_EMAIL }} \
            --build-arg TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} \
            --build-arg TEST_EMAIL_SUB=${{ secrets.TEST_EMAIL_SUB }} \
            --build-arg TEST_PASSWORD_SUB=${{ secrets.TEST_PASSWORD_SUB }} \
            --build-arg ENABLE_TEST_LOGS=${{ secrets.ENABLE_TEST_LOGS }} \
            .
      - name: 'Start Docker Container'
        run: |
          docker run -d --name forvoyez-container -p 3000:3000 \
            -e NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} \
            -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            -e CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            -e NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
            -e NEXT_PUBLIC_CLERK_SIGN_OUT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_OUT_URL }} \
            -e MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }} \
            -e MAILGUN_API_URL=${{ secrets.MAILGUN_API_URL }} \
            -e MAILGUN_PUBLIC_KEY=${{ secrets.MAILGUN_PUBLIC_KEY }} \
            -e MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e LEMON_SQUEEZY_API_KEY=${{ secrets.LEMON_SQUEEZY_API_KEY }} \
            -e LEMON_SQUEEZY_STORE_ID=${{ secrets.LEMON_SQUEEZY_STORE_ID }} \
            -e LEMON_SQUEEZY_WEBHOOK_SECRET=${{ secrets.LEMON_SQUEEZY_WEBHOOK_SECRET }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e TEST_EMAIL=${{ secrets.TEST_EMAIL }} \
            -e TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} \
            -e TEST_EMAIL_SUB=${{ secrets.TEST_EMAIL_SUB }} \
            -e TEST_PASSWORD_SUB=${{ secrets.TEST_PASSWORD_SUB }} \
            -e ENABLE_TEST_LOGS=${{ secrets.ENABLE_TEST_LOGS }} \
            forvoyez:test pnpm run start
      - name: 'Wait for the application to be ready'
        run: |
          echo "Waiting for the application to be ready..."
          end=$((SECONDS+10))
          while [ $SECONDS -lt $end ]; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Application is up!"
              exit 0
            fi
            echo "Waiting for the application to be up..."
            sleep 5
          done
          echo "Application did not start in time"
          docker logs forvoyez-container
          exit 1
      - name: 'Run E2E Tests'
        run: pnpm test:e2e:general
        env:
          NEXT_PUBLIC_URL: http://localhost:3000
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_EMAIL_SUB: ${{ secrets.TEST_EMAIL_SUB }}
          TEST_PASSWORD_SUB: ${{ secrets.TEST_PASSWORD_SUB }}
      - name: 'Stop and remove Docker Container'
        run: |
          docker stop forvoyez-container
          docker rm forvoyez-container
