name: 'Test'
on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, gulp, prettier, vitest]
      - name: 'Install Playwright Browsers'
        run: pnpm exec playwright install
      - name: 'Run Unit and Integration Tests'
        run: pnpm test:ci
      - name: 'Run ESLint'
        run: pnpm lint
      - name: 'Run E2E Tests'
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: pnpm test:e2e
      - name: 'Run E2E General Tests'
        if: github.event_name == 'pull_request'
        run: pnpm test:e2e:general
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
